### ISSUE TITLE
Calculate refractive index from a formula

### ISSUE THREAD

**Issue by garrekstemo** [garrekstemo/TransferMatrix.jl#18]
Calculate the refractive index from a dispersion formula using [RefractiveIndex.jl](https://github.com/stillyslalom/RefractiveIndex.jl) when loading data.

**Comment by stillyslalom** [comment]
You may want to use [`dispersion`](https://stillyslalom.github.io/RefractiveIndex.jl/dev/#RefractiveIndex.dispersion-Tuple{RefractiveMaterial,%20Float64}), which is implemented for both tabular and formula data. If you're open to a significant revision of how layers are constructed, I'd suggest moving to something like what [ABCDMatrixOptics.jl](https://github.com/JuliaPhysics/ABCDMatrixOptics.jl) uses:
1. Assemble optical elements 'in the dark'
2. Simulate wave propagation through the elements at one or more wavelengths

This would make it easier to handle dispersion formula materials, as well as assemblies with both formula and tabulated data.

**Comment by garrekstemo** [comment]
Thanks, I'll take a look at it. There are a few modifications I'd like to make, so now might be a good time to look over the code base.
