### ISSUE TITLE
p-pol, s-pol ordering in 4x4 TMM formalism

### ISSUE THREAD

**Issue by DEKOHG** [garrekstemo/TransferMatrix.jl#22]
Looking through your code, it looks like in your 4x4 transfer matrix formulation has a opposite ordering to Yeh' s book p246 - 247. (Yeh Pochi. 2005. Optical Waves in Layered Media. Hoboken NJ: Wiley.) In Yeh's book, he ordered the s-pol in the upper half of the vector and p-pol in the lower, while your implementation seems to reverse such ordering and hence, your s, p subscripts are swapped compared with Eq. (9.7-23) - (9.7-30) in Yeh's book. I guess it may be helpful to include that in the documentation to avoid confusion? Maybe something like Eq. (9.7-22) in Yeh's book but with your ordering scheme would suffice as a clarification? Thank you.

**Comment by garrekstemo** [comment]
I can see where that would cause confusion. The calculation method comes from Yeh, but the ordering comes from Passler and Paarmann, 2017 (DOI: 10.1364/JOSA.69.000742). I'll edit the doc string.

**Comment by DEKOHG** [comment]
I see where that came from now. Could you also confirm if you are using exp(jwt) or exp(-jwt) convention in you code? Thanks.

**Comment by garrekstemo** [comment]
The convention is exp(-jwt). But the propagation matrix does not follow Yeh's original formulation. The eigenmodes are sorted into reflected and transmitted, real and complex waves to avoid numerical instabilities. These eigenmodes appear in the propagation matrix and determine the sign of each term in the exponential. This is in eq 12 in Passler and Paarmann, 2017 but originally comes from Li et al, 1998 (DOI:10.1364/AO.27.001334).
